### ISSUE TITLE
Finalize client SDK APIs (for go and js sdks)

### ISSUE THREAD

**Issue by talkol** [orbs-network/orbs-client-sdk-go#5]
# Import the library

### golang

```go
import "github.com/orbs-network/orbs-client-sdk-go/orbsclient"
```

### javascript

```js
const Orbs = require("orbs-client-sdk");
```

# Working with accounts

### golang

```go
type OrbsAccount struct {
    PublicKey  []byte
    PrivateKey []byte
    Address    string // hex starting with 0x
}
account, err := orbsclient.CreateAccount()
```

### javascript

```js
interface Account {
  publicKey: Uint8Array;
  privateKey: Uint8Array;
  address: string; // hex starting with 0x
}
const account = Orbs.createAccount();
```

# Initializing the client

### golang

```go
const virtualChainId = 42
client := orbsclient.NewOrbsClient("http://node-endpoint.com", virtualChainId, codec.NETWORK_TYPE_TEST_NET)
```

### javascript

```js
const virtualChainId = 42;
const client = new Orbs.Client("http://node-endpoint.com", virtualChainId, "TEST_NET");
```

# Sending a transaction (of 10 tokens)

### golang

```go
tx, txId, err := client.SignTransaction(
    account.PublicKey,
    account.PrivateKey,
    "BenchmarkToken",
    "transfer",
    uint64(10), orbsclient.AddressToBytes("j1Q1Y54mCcVfR5jVAQMMJEy6VbZEtYeM3R"))
// tx is []byte
// txId is string (hex starting with 0x)
transferResponse, err := client.SendTransaction(tx)
```

### javascript

```js
const [tx, txId] = client.signTransaction(
    account.publicKey,
    account.privateKey,
    "BenchmarkToken",
    "transfer",
    [ Orbs.ArgUint64(10), Orbs.ArgAddress("j1Q1Y54mCcVfR5jVAQMMJEy6VbZEtYeM3R") ]);
// tx is Uint8Array
// txId is string (hex starting with 0x)
const transferResponse = await client.sendTransaction(tx);
```

# Get transaction status

### golang

```go
statusResponse, err := client.GetTransactionStatus(txId)
```

### javascript

```js
const statusResponse = await client.getTransactionStatus(txId);
```

# Call method

### golang

```go
balanceResponse, err = client.CallMethod(
    account.PublicKey,
    "BenchmarkToken",
    "getBalance",
    orbsclient.AddressToBytes("j1Q1Y54mCcVfR5jVAQMMJEy6VbZEtYeM3R"))
```

### javascript

```js
const balanceResponse = await client.callMethod(
    account.publicKey,
    "BenchmarkToken",
    "getBalance",
    [ Orbs.ArgAddress("j1Q1Y54mCcVfR5jVAQMMJEy6VbZEtYeM3R") ]
  );
```

# Private key vault

Many client SDKs wrap private key access by providing a "vault" object that manages the accounts, signs transactions and does not give direct access to the private key.

We prefer to move this functionality outside the scope of this SDK. Most practical vaults are highly dependent on the environment, a vault for iOS is implemented differently than one for Android, and a vault for client-side web is different from one for a server. Providing a naive memory based vault will not really solve the problem for developers. We will have to provide separate repos that implement practical vaults per environment.

Until those are available, we delegate this responsibility to users of the SDK.

**Comment by OdedWx** [comment]
Few thoughts:
1. CreateAccount should be able to receive entropy/nemonic.
2. Add support for multi-account deterministic wallets derived from {secret, index}, consider native support in account(index)
3. NewOrbsClient - review endpoint per virtual chain, network type
4. AddressToByte, ArgAddress and different semantics - one translates and one passes an address argument (for example to allow address validation), consider orbsclient.Address

**Comment by talkol** [comment]
Please also prioritize what's blocker for V1 and what's nice to have

**Comment by EsterEdelstein** [comment]
of course!

**Comment by netoneko** [comment]
I have two issues: 

1. in golang when you call the contract you don’t pass an array of arguments which is confusing compared to its JS counterpart
2. You call a helper function addressToBytes, why not just pass a string?

**Comment by electricmonk** [comment]
why not:
```golang
client := orbs.NewClient("http://node-endpoint.com", virtualChainId, codec.NETWORK_TYPE_TEST_NET)
```

**Comment by electricmonk** [comment]
Also, regarding vcid and network type - we're not sure yet how the node http router will look, so maybe network type is out of scope here?
